### ISSUE TITLE
Leaky heartbeat logic

### ISSUE THREAD

**Issue by samcday** [thibauts/node-castv2-client#29]
I'm seeing this in the logs when I have a long-running daemon that uses castv2-client:

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at HeartbeatController.addListener (events.js:160:15)
    at HeartbeatController.once (events.js:185:8)
    at HeartbeatController.ping (/srv/atlascast-server/node_modules/castv2-client/lib/controllers/heartbeat.js:38:8)
    at oninterval (/srv/atlascast-server/node_modules/castv2-client/lib/controllers/heartbeat.js:60:10)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

Looking at the code for `heartbeat.js`, I'm wondering if it should perhaps be aborting ping() calls if there's already one in progress?

**Comment by thibauts** [comment]
Sure. My impl is a bit crude. This code shouldn't use `setInterval` at all. Pings should be relaunched on pong. It would make the code much simpler, too.

If you make a PR for this I'll merge it faster this time, promise :)
