### ISSUE TITLE
TypeError: Cannot read property 'stop' of null

### ISSUE THREAD

**Issue by WeeJeWel** [thibauts/node-castv2-client#55]
```
TypeError: Cannot read property 'stop' of null
    at Client.onclose (/node_modules/castv2-client/lib/senders/platform.js:42:21)
    at Client.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Client.emit (events.js:166:7)
    at TLSSocket.onclose (/node_modules/castv2-client/node_modules/castv2/lib/client.js:59:10)
    at TLSSocket.g (events.js:260:16)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:486:12)
```

Seems that the heartbeat isn't initialized

**Comment by thibauts** [comment]
Are you catching error events as in the readme exemple code ?
