### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]:

### ISSUE THREAD

**Issue by jth62** [thibauts/node-castv2-client#86]
Hello I use the plugin assistant plugin for my google home, this one uses this plugin. Unfortunately I have the following message that prevents the plugin from working properly:

[assistant-notifier] (host) Reading the message: 'this is a test'
{[Function: callback] port: 8009, rejectUnauthorized: false}
(node: 31285) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received type function
    at lookupAndConnect (net.js: 934: 13)
    at TLSSocket.Socket.connect (net.js: 914: 5)
    at Object.connect (_tls_wrap.js: 1298: 13)
    at Client.connect (/home/pi/assistant-plugins/node_modules/assistant-notifier/node_modules/castv2-client/node_modules/castv2/lib/client.js:35:21)
    at PlatformSender.connect (/home/pi/assistant-plugins/node_modules/assistant-notifier/node_modules/castv2-client/lib/senders/platform.js:27:15)
    at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:33:13
    at new Promise (<anonymous>)
    at AssistantNotifier.prom (/home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:28:10)
    at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:78:15
    at Array.forEach (<anonymous>)
(node: 31285) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated from the inside of the outside world, but it was not handled by .catch (). (rejection id: 2)
(node: 31285) [DEP0018] DeprecationWarning: unhandled promised rejections are deprecated. In the future, it will not be possible to terminate the Node.js process with a non-zero exit code.

Can you help me please?
Thank you in advance,

**Comment by jeanabraham** [comment]
Did you ever find the solution to this, @jth62? I'm running into a similar error.

```
Express server listening on http://127.0.0.1:9000
loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. ../../../../../../../.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/strong-arc-project-list/node_modules/loopback/server/middleware/rest.js:60:32
Error: The "options.port" property must be one of type number or string. Received type object
Unexpected error: TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received type object
TypeError [ERR_INVALID_ARG_TYPE]: The "options.port" property must be one of type number or string. Received type object
    at lookupAndConnect (net.js:990:13)
    at TLSSocket.Socket.connect (net.js:969:5)
    at TLSSocket.connect (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/async-listener/index.js:138:27)
    at Object.connect (_tls_wrap.js:1434:13)
    at Agent.createConnection (https.js:125:22)
    at Agent.createSocket (_http_agent.js:242:26)
    at Agent.addRequest (_http_agent.js:201:10)
    at Agent.addRequest (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/async-listener/index.js:157:21)
    at new ClientRequest (_http_client.js:276:16)
    at Object.request (https.js:309:10)
    at Request.start (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/request/request.js:751:32)
    at Request.end (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/request/request.js:1511:10)
    at end (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/request/request.js:564:14)
    at Immediate._onImmediate (/Users/jean/.nvm/versions/node/v12.14.1/lib/node_modules/apiconnect/node_modules/request/request.js:578:7)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
